# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task1app', '0002_auto_20160712_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_date', models.DateTimeField(auto_now_add=True, verbose_name='Publish Data')),
                ('choice_dislike', models.IntegerField(default=0)),
                ('choice_like', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task1app.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
