# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1app', '0003_auto_20160713_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_like',
            field=models.IntegerField(default=0),
        ),
    ]
