# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1app', '0004_auto_20160713_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_dislike',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_like',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_dislike',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_like',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
